server:
  port: 8080
spring:
  datasource:
    name: PostGreSQL
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/edutrack
    username: lyra
    password: "@19172366630Zhou"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false