server:
  port: 8080
spring:
  datasource:
    name: PostGreSQL
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/edutrack
    username: lyra
    password: "@19172366630Zhou"
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# SpringDoc OpenAPI configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html